name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Setup sccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}
        max-size: 1000M
        variant: sccache
    - name: build
      run: ./scripts/build.sh
    - name: test
      run: ./scripts/test.sh
