name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true  # Ensure git submodules are checked out
    
    - name: Setup sccache
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}
        max-size: 1000M
        variant: sccache

    - name: Set up dependencies
      run: |
        sudo apt update
        sudo apt install llvm-15-dev ninja-build cmake clang -y


    - name: Build
      run: ./scripts/build.sh
    
    - name: Test
      run: ./scripts/test.sh
